### ISSUE TITLE
Suggestions: Button to minimize UI

### ISSUE THREAD

**Issue by Exslims** [Just2good/TFT-Overlay#107]
An overlay is always visible which is annoying when you altabbing from the game, the suggestion is to add "hide" button near "opacity" button, which minimizes UI.

**Comment by Just2good** [comment]
Have you tried the Auto-Dim function?

**Comment by Exslims** [comment]
@Just2good auto-dim enabled, I think you don't understand me, I mean 
![image](https://user-images.githubusercontent.com/11871586/62411177-67d86180-b600-11e9-8be9-19cc9dbb5c9e.png)

Minus button -> hide UI in the red region, Plus - expand

**Comment by Exslims** [comment]
And I can't reopen this ticket, why you close it?)

**Comment by Just2good** [comment]
There is another function called Always on top, you can disable it so it goes in the background until its enabled again, but I know what you are talking about. Try the option out and tell me if it's still an issue

**Comment by Exslims** [comment]
@Just2good It is about UX, I would like to have always on top but minimize UI when I need it. This tool mostly always on top, but now to hide UI I need click on the corner, mouse over on preference - click on always on top and I need to do the same thing to turn it back, all of that can be replaced by minimizing button, for example I need minimize always in LOL client because mostly PLAY button is under overlay and I need to move out overlay.

**Comment by Xs3roN** [comment]
I dont see a point in having minimize button. When you are in game, you use the overlay, when you are done with a match you minimize it the same as you do with app and windows - clicking on taskbar. 

**Better suggestion is to have keybind to show and hide the overlay.**

**Comment by widget-** [comment]
I think the more common name for this feature is "Collapse" or "Shade".

Basically (with the current UI at least) it would make sense for clicking the tab that's already open to hide that tab's contents. E.g. if you click `Main` to go to the main tab, then click `Main` again, now "no" tabs will be open and it will take up very little space on the screen.

Admittedly the main tab is pretty compact as it is, but I wouldn't mind seeing this anyway since you won't always need it even in-game (beginning of games waiting to take damage for the slow income-based strats.)

**Comment by widget-** [comment]
Here's a simple but hopefully more clear mock-up of what OP was suggesting

![image](https://user-images.githubusercontent.com/7691630/64033011-35dbf180-cb11-11e9-9295-e33e0e674d67.png)
