### ISSUE TITLE
Majour FPS Drop

### ISSUE THREAD

**Issue by Basilicum** [Just2good/TFT-Overlay#18]
Game runs at 200FPS usually. With this Overlay on, its tanking down to 15FPS and less. How even?
Otherwise this is an amazing app, just wish it wasn't so heavy on the FPS.

**Comment by Just2good** [comment]
Does the FPS drop after clicking on the overlay? Is it fine after clicking in the game again? If both of these are true, it's because League goes into background when clicking on the overlay and the LoL client throttles the game resources whenever it's in the background. One of the reasons why I added a hover option so you don't need to click if you don't want to.

**Comment by Basilicum** [comment]
If I click on the Overlay, League does indeed go into the Background and drop down to 15FPS. Hwoever, even with clicking onto league, its still about 30fps less than usual, which is still odd. But this is a good tipp.

**Comment by Just2good** [comment]
Closing, the only way to fix this fps issue is to hook to client, which is a sketchy subject
