### ISSUE TITLE
Suggestion: Close overlay button

### ISSUE THREAD

**Issue by dengneos** [Just2good/TFT-Overlay#51]

**Comment by dengneos** [comment]
Adding a button to close the entire program instead of going into the Task Manager to shut down the process would be nice

**Comment by novatorem** [comment]
You can close it by:

- Right clicking the orange box on the right and clicking Exit
- Right clicking the program from the task bar and exiting there
- Alt + F4 when it's in focus

But I feel a close button might clutter things more than needed? Maybe Esc can be used but otherwise an X is too hard to get on a small application.

**Comment by dengneos** [comment]
It doesn't show up on my taskbar and right clicking the orange box did nothing. I guess I'll just Alt +F4

**Comment by Just2good** [comment]
What OS are you using? I want to know why you aren't getting the context menu from right clicking the orange box.

**Comment by dengneos** [comment]
Windows 10 Home Ver. 1809

**Comment by Just2good** [comment]
If you still get this issue, please open up another post, I can't seem to replicate this and other people can open up the context menu just fine. That being said, there will be a new context menu redesign that should help.
