### ISSUE TITLE
add a reset button in item builder tab

### ISSUE THREAD

**Issue by TakashiOkada23** [Just2good/TFT-Overlay#69]
I have to manually reset every time I use and get new items constantly. a little reset button would help a lot

PS. would also love the old, smaller design to be available to switch to if possible. it was more comfortable because it didn't take so much space on the screen, less confusing to find the icons when put on top of text, i loved that it was especailly less tall too.  

ps. 2: there's also a bug? that when I drag the window to the top it locks itself to the top left corner and can't restore it without closing and opening again

**Comment by Just2good** [comment]
Reset button is in my test project atm so it will come out soon. There will be an old default skin but its not high priority atm (Super easy to implement though and will most likely be added in if we get a TFT API). The snapping to top basically makes the program fullscreen and bugs it out this is because of windows itself and most likely has no solution to prevent it.
